# Generated by Django 3.2.9 on 2021-11-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
