# Generated by Django 3.2.9 on 2021-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=20)),
                ('crm', models.CharField(max_length=15)),
                ('especialidade', models.CharField(default=None, max_length=60)),
                ('foto', models.ImageField(blank=True, upload_to='foto_produto/%y/%m/%d/')),
            ],
        ),
    ]
