# Generated by Django 3.2.9 on 2021-11-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
