# Generated by Django 3.2.9 on 2021-11-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cadastro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
