# Generated by Django 3.2.9 on 2021-11-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=None)),
                ('horario', models.CharField(choices=[('A', '9:00'), ('B', '10:00'), ('C', '11:00'), ('D', '12:00'), ('E', '13:00'), ('F', '14:00'), ('G', '15:00')], max_length=1)),
                ('mostrar', models.BooleanField(default=True)),
                ('medicos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.medico')),
            ],
        ),
    ]
