# Generated by Django 3.2.5 on 2021-11-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_agendamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.CharField(choices=[('9 AM', '09:00:00'), ('10 AM', '10:00:00'), ('11 AM', '11:00:00'), ('12 PM', '12:00:00'), ('1 PM', '13:00:00'), ('2 PM', '14:00:00'), ('3 PM', '15:00:00')], max_length=10),
        ),
    ]
